columns:
- online_order
- book_table
- rate
- votes
- listed_in(type)
- rate
- listed_in(city)

numerical_columns:
- votes
- rate

drop_columns:
- url
- address
- name
- phone
- location
- rest_type
- dish_liked
- reviews_list
- menu_item
- cuisines